version: "3"

services:
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - 80:80
    networks:
      - frontend
    deploy:
      replicas: 2

  redis:
    image: redis:3.2
    networks:
      - frontend

  worker:
    image: bretfisher/examplevotingapp_worker:java
    networks:
      - frontend
      - backend

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - backend

  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - 5001:80
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend:
