version: "3.2"

services:
  drupal:
    image: "drupal:8.2"
    ports:
      - "8080:80"
    volumes:
      - "drupal-modules:/var/www/html/modules"
      - "drupal-profiles:/var/www/html/profiles"
      - "drupal-sites:/var/www/html/sites"
      - "drupal-themes:/var/www/html/themes"

  database:
    image: "postgres:12.1"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/database_pass
    volumes:
      - drupal-data:/var/lib/postgresql/data
    secrets:
      - database_pass

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:

secrets:
  database_pass:
    external: true
