version: "2"

services:
  drupal:
    image: "drupal:8"
    container_name: drupal
    ports:
      - "8080:80"
    volumes:
      - "drupal-modules:/var/www/html/modules"
      - "drupal-profiles:/var/www/html/profiles"
      - "drupal-sites:/var/www/html/sites"
      - "drupal-themes:/var/www/html/themes"

  postgres:
    image: "postgres:12"
    container_name: postgres
    environment:
      POSTGRES_DB: drupal-db
      POSTGRES_USER: drupal-user
      POSTGRES_PASSWORD: drupal-pass
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  postgres-db:
