version: '3.7'

services:
    drupal:
      image: drupal:8-apache
      ports:
        - 8080:80
      volumes:
        - /var/www/html/modules
        - /var/www/html/profiles
        - /var/www/html/themes
        - drupal-sites:/var/www/html/sites
    postgres:
      image: postgres:10
      environment:
        POSTGRES_PASSWORD: root

volumes:
    drupal-sites: